services:
  mcp-agent-web:
    image: mcp-agent-web
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: mcp-agent
    ports:
      - "8000:8000"
    volumes:
      - ./mcp_server_config.json:/app/mcp_server_config.json
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s 